"""Cria tabela turmas

Revision ID: 819bdd987e3f
Revises: 
Create Date: 2025-09-15 11:57:43.989257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819bdd987e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cod_turma', sa.String(length=50), nullable=False),
    sa.Column('materia', sa.String(length=255), nullable=True),
    sa.Column('dna', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_cod_turma'), 'turmas', ['cod_turma'], unique=True)
    op.create_index(op.f('ix_turmas_id'), 'turmas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turmas_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_cod_turma'), table_name='turmas')
    op.drop_table('turmas')
    # ### end Alembic commands ###
