services:
  db:
    image: postgres:15-alpine 
    restart: always
    environment:
      POSTGRES_DB: ada
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: